# fly.toml app configuration file generated for restless-frost-9292 on 2023-05-10T18:11:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restless-frost-9292"
primary_region = "lhr"

[env]
  PORT = "8080"
  JWT_SECRET="aboba"
  URL="https://restless-frost-9292.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
